/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: dU9SZPrnMUWLfHqMrxdfvS

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsfkLVulOIgg56 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: fkLVulOIgg56/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsfkLVulOIgg56
});
